# http://localhost:3001/api/v1/products

# http://localhost:3001/api/v1/products/6327ea0a4e02b3a97cae1a42
#http://localhost:3001/api/v1/products/6327ea0a4e02b3a97cae1a

GET http://localhost:3001/api/v1/products

###

POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
	"email": "bar@example.com",
	"password": "12345"
}

POST http://localhost:3001/api/v1/users/register
Content-Type: application/json

{
	"username": "hoge",
	"email": "hoge@example.com",
	"password": "12345",
	"confirmPassword": "12345"
}

###

POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
    "email": "hoge@example.com",
    "password": "12345"
}

###

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJhY2M1NTljOWIxMzY2OGIxZmM0NmQiLCJ1c2VybmFtZSI6ImhvZ2UiLCJpYXQiOjE2NjM4MzY4MzIsImV4cCI6MTY2Mzg0MDQzMn0.uojlU21J-9meEccem9Y5GQAJioMJenHFksRxSdCCxRM

GET http://localhost:3001/api/v1/products/authTest
Content-Type: application/json
Authorization: {{token}}


